apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2023mt03525
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: 753572177160.dkr.ecr.us-east-1.amazonaws.com/devops-repo:img-2023mt03525
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: config-2023mt03525
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name